### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by cale148** [FuzzyCmd/FuzzyCmd#1]
Create logo 
16,19,38,64,128px
format PNG

**Comment by eshill** [comment]
![16](https://cloud.githubusercontent.com/assets/11502920/25479348/3232821c-2b4d-11e7-8d34-219936309862.png)
![19](https://cloud.githubusercontent.com/assets/11502920/25479351/3233e8e6-2b4d-11e7-9433-f1e65f321e2f.png)
![38](https://cloud.githubusercontent.com/assets/11502920/25479349/3233c848-2b4d-11e7-87e3-ac4270a7321b.png)
![64](https://cloud.githubusercontent.com/assets/11502920/25479350/3233b268-2b4d-11e7-8a37-d8ef14e74ade.png)
![128](https://cloud.githubusercontent.com/assets/11502920/25479352/323490b6-2b4d-11e7-90be-8fdff5ba635e.png)
